### ISSUE TITLE
Why is there a black "X" next to the search bar? 

### ISSUE THREAD

**Issue by ClubService** [unsupo/maps-event-app#21]
Black X does not do anything that I'm aware of

**Comment by unsupo** [comment]
Black x clears the search bar at the top of the map as well as removes all found results from the search bar.

**Comment by unsupo** [comment]
It appears to work as expected.
![screen shot 2017-10-23 at 12 32 14 pm](https://user-images.githubusercontent.com/18237013/31906403-41f1d4e0-b7ee-11e7-9228-02368fc4d23f.png)
Searched for and found mcdonalds near me.

![screen shot 2017-10-23 at 12 32 23 pm](https://user-images.githubusercontent.com/18237013/31906424-4e7bc02c-b7ee-11e7-95cc-6e44de31429c.png)

Pressed x clearing the results

**Comment by ClubService** [comment]
Is that something that google provides or did you make that?

**Comment by unsupo** [comment]
I made it.

**Comment by ClubService** [comment]
Ok

**Comment by unsupo** [comment]
Why?
